Pimp my app
SiMDE-Projects/jeffrey pull request #20
Opened 2020-10-27 23:26 UTC by maxime-vaillant

2020-10-28 09:33 UTC, cesar-richard requested changes

2020-10-28 09:33 UTC, cesar-richard commented on src/App.js
> +    const [order, setOrder] = useState([]);
Etant donné que t'as un state "order", je comprend pas l'intérêt de states count et total

2020-10-28 09:33 UTC, cesar-richard commented on src/App.js
> +        setOrder(tmp);
Quand meme un peu crado ce map a l'arrache.
et const tmp = order copie la référence de la variable , donc tu risques de faire muter le state

2020-10-28 09:33 UTC, cesar-richard commented on src/context/total-context.js
> +    count: 0,
Pareil , je pige pas pourquoi tu fais pas tout avec le total ^^

2020-10-28 10:18 UTC, maxime-vaillant commented on src/App.js
> +    const [order, setOrder] = useState([]);
Bah oui je peux faire sans, mais ça évite de traiter ces infos en faisant des map à chaque fonction, après c'est quoi le plus optimiser ? faire comme ça, ou passer par un map systématique

2020-10-28 18:30 UTC, cesar-richard commented on src/App.js
> +    const [order, setOrder] = useState([]);
C'est pas des map mais un reduce que tu devrais faire, et etant donné que je vois mal un jean michel commander 8 millions d'articles (auquel cas : cheh) , on peut re reduce 2 fois la meme liste. 
Par contre je préfère qu'on reduise l'empreinte mémoire en ne stockant pas 2 fois les infos equivalentes

2020-10-28 18:35 UTC, cesar-richard requested changes

2020-10-28 18:35 UTC, cesar-richard commented on .github/actions/translations.js
> -	return `${read ? '../../' : './'}src/locales/${locale}/translation.json`;
Touches pas a ca stp ;)

2020-10-28 18:35 UTC, cesar-richard commented on .github/actions/translations.js
> +	let regexes = [`t\\([\\"']([a-zA-Z_0-9.]+)['\\"](\\,|\\))`, `i18nKey=[\\"']([a-zA-Z_0-9.]+)['\\"]`];
ni a ca, en gros : touches pas aux dossier .github ^^

2020-10-28 18:35 UTC, cesar-richard commented on .github/workflows/check-i18n.yml
> +#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
same, pas touche

2020-10-28 18:35 UTC, cesar-richard commented on .eslintrc.json
> +                "react/prop-types": "off"
Laisse ce fichier tranquille aussi ^^

2020-10-28 18:35 UTC, cesar-richard commented on src/components/ressources/Produit.js
> +                <h1>{value !== undefined ? value.count : 0}</h1>
tu peux faire `value ? value.count : 0` directement. undefined est percu comme false

2020-10-28 20:48 UTC, maxime-vaillant commented on src/App.js
> +        setOrder(tmp);
Si ça mute c'est pas gênant ? Enfin dans tout les cas, si à la fin ça fait setOrder(order) ça revient au même ?

2020-10-28 20:49 UTC, maxime-vaillant commented on src/App.js
> +    const [order, setOrder] = useState([]);
Je comprends ton argument de la mémoire ! Je vais tâcher de comprendre l'utilisation des reduceurs

2020-10-30 13:59 UTC, cesar-richard commented on src/App.js
> +        setOrder(tmp);
C'est très génant, le state est censé etre immutable. Tu n'as le droit que de le lire.

2020-10-30 14:08 UTC, maxime-vaillant commented on src/App.js
> +        setOrder(tmp);
Comment je copie uniquement une valeur dans ces cas là ?

2020-10-30 14:27 UTC, noeamiot commented on src/App.js
> +        setOrder(tmp);
Je suis d'accord avec @cesar-richard pour la map, il y a d'autres fonctions qui font ce taff en plus propre, du côté de filter() par exemple

2020-10-30 14:32 UTC, noeamiot commented on src/App.js
> +    const [order, setOrder] = useState([]);
Clairement, vu que tu peux déterminer sans trop de peine total et count depuis order, en rajoutant des doublons tu risques plus d'avoir des problèmes de cohérence des données (plus un problème de render multiples en cas d'actualisation que césar voulait mettre en avant).

2020-10-30 15:17 UTC, maxime-vaillant commented on src/App.js
> +        setOrder(tmp);
La fonction filter remplacera peut être mon if, mais pas le map ! Et ça répond à pas la question de la constante immuable

2020-10-30 18:51 UTC, cesar-richard requested changes

2020-10-30 18:51 UTC, cesar-richard commented on src/App.js
> +        });
tout ca c'est juste `const item = order.find(x=>x.id===id);`

2020-10-30 18:51 UTC, cesar-richard commented on src/App.js
> +    function handleOrder1(id, prix) {
wtf handleOrder1 ?

2020-10-30 18:51 UTC, cesar-richard commented on src/App.js
> +        setOrder(tmp);
dans l'esemble y'a moyen de se passer de tout ca en enregistrant a chaque clique 1 article dans l'order et pas un objet qui compte des données aggrégées, @noeamiot saura t'expliquer

2020-10-30 20:49 UTC, noeamiot commented on src/App.js
> +        setOrder(tmp);
Globalement t'as tout dit mais pour détailler, étant donné le type et la quantité de données que ça représente, on n'a pas forcément à de gérer la quantité par article directement. Tu peux simplement ajouter tes items dans ton tableau order et le compte est en fait une agrégation (en rassemblant par articles identiques, on regarde combien il y a de chaque).

2020-10-31 18:59 UTC, cesar-richard approved these changes

2020-10-31 19:00 UTC, merged

2020-10-31 19:00 UTC, noeamiot approved these changes

2020-10-31 19:04 UTC, cesar-richard commented
@all-contributors please add @noeamiot for review, userTesting, doc and projectManagement

2020-10-31 19:05 UTC, cesar-richard commented
@all-contributors please add @noeamiot for review, userTesting, doc and projectManagement